# **Untitled3**

# Python物件
List[串列] Tuple(元組) Dictionary{字典} Sets{集合}<br>
List[串列]<br>


# 使用中括號[]包裹元素

In [1]:
expenses = [1138, 101, 12, 300, 2049]
print(sum(expenses))

3600


# 索引

In [2]:
expenses = [1138, 101, 12, 300, 2049]
print(expenses[0]) #索引從0開始
print(expenses[1])
print(expenses[-1]) #倒數第一個
print(expenses[-2])

1138
101
2049
300


In [3]:
my_list0 = [] #空串列
my_list1 = list() 
my_list2 = ['python', 'javascript', 'C#']
print(my_list2[0])

python


# list的長度

In [4]:
my_list2 = ['python', 'javascript', 'C#']
print(len(my_list2))
print(len(my_list2[0]))

3
6


# 附加

In [5]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.append('java')
print(my_list2)

['python', 'javascript', 'C#', 'java']


In [6]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.insert(1,'java')
print(my_list2)

['python', 'java', 'javascript', 'C#']


# 刪除

In [7]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.remove('python') #移除指定元素
print(my_list2)
del my_list2[-1] #刪除指定位置的元素
print(my_list2)
my_list2.clear() #清除全部
print(my_list2)

['javascript', 'C#']
['javascript']
[]


In [8]:
a=[1,2]
print(a*5)

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]


# list取值

In [9]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3] #範圍取值，0,1,2不包含3
print(b)
c=a[0:9:2] #間隔2取值
print(c)
d = a[0: ]
print(d)
e = a[ :9]
print(e)
f = a[:] #取全部值
print(f)

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [10]:
a=[1,2,3,4,5,6,7,8,9]
del a[7:9] #刪除某範圍值, 7, 8
print(a)
print(min(a)) #最小值
print(max(a)) #最大值
print(a.index(1)) #找出1所在的第一個索引值
b=[1,0,0,1,1,1]
print(b.count(1)) #1出現的次數
a.reverse() #串列反轉
print(a)
a.sort() #串列由小到大排序,a的值會被改變
print(a)

[1, 2, 3, 4, 5, 6, 7]
1
7
0
4
[7, 6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6, 7]


In [ ]:
expenses = [1138, 101, 12, 300, 2049]
s=sorted(expenses) #expenses的值不會變
print(s, expenses)

5/3

In [ ]:
#List[串列]
score=[90,70,80,88,95]
print(score[0])
print(score[1])
print(score[4])
print(score[-1]) #-1從最後面屬過來第一個

90
70
95
95


In [ ]:
score=[90,70,80,88,95]
print(score[0:3])
print(score[:3])
print(score[3:])
print(score[:])

[90, 70, 80]
[90, 70, 80]
[88, 95]
[90, 70, 80, 88, 95]


In [ ]:
score=[90,70,80,88,95]
print(score[0:5:2])
print(score[::2])
print(score[4:0:-1])
print(score[0:4:-1])

[90, 80, 95]
[90, 80, 95]
[95, 88, 80, 70]
[]


In [ ]:
astr="abcdefghijklmopqrstuvwxyz"
print(astr[0])
print(astr[-1])
print(astr[5:20])
print(astr[5:20:3])

a
z
fghijklmopqrstu
filps


# **Untitled4**<br>
# numpy套件(numeric python)

為什麼需要numpy?


*   numpy由c撰寫，速度快python 10~1000倍以上
*   numpy儲存結果較正確，python數字儲存不正確
*   numpy節省記憶體儲存空間
*   numpy的向量(矩陣計算)速度快
*   numpy的取值方便








In [11]:
a_list=[1,2,3,4,5]
print(a_list*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np
a=np.array([1,2,3,4,5])
print(a*3)

In [24]:
import numpy as np
z=np.zeros(6)
print(z)
print(np.empty((2,3,4)))
print(np.arange(10))

[0. 0. 0. 0. 0. 0.]
[[[1.32048490e-316 6.76869935e-322 0.00000000e+000 0.00000000e+000]
  [0.00000000e+000 5.30276956e+180 6.00736842e-067 4.09940685e+097]
  [3.70304290e-033 4.09868439e+126 4.25223142e+180 7.48543529e+247]]

 [[2.32363010e+251 6.11130817e+223 2.59903818e-144 2.14828425e+184]
  [4.90483246e-062 4.51427601e-090 8.84738251e+165 2.59027859e-144]
  [1.16442250e-028 9.44872517e-143 6.17582057e-322 0.00000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


# **ndarray的進階操作**

In [25]:
my_array=np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5])

[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


# 2維資料取值

In [26]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array)
print(my_2d_array[1,:])
print(my_2d_array[:,1])
print(my_2d_array[1,1])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [27]:
my_array=np.arange(0,10)
print(my_array)
print(my_array.shape)
my_2d_array=my_array.reshape(2,5)
print(my_2d_array)
print((np.arange(0,100).reshape(10,10)))

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


# numpy的空值nan

In [28]:
b=np.array([56, 8, 19, 14, np.nan])
print(b)

[56.  8. 19. 14. nan]


# **Untitled5** 

# 函式

*   獨立的一組程式碼，可以重複使用
*   通常可以有0-多個輸入參數，0-1輸出
*   函式輸入參數可以有預設值

In [29]:
#傳統的程式寫法
import math
radius=eval(input("請輸入圓的半徑"))
area=radius*radius*math.pi
print("圓的面積:",area)

請輸入圓的半徑10
圓的面積: 314.1592653589793


# 錯誤處理
try;<br>
(需要檢測的程式碼)<br>
except;<br>
(錯誤的處理方式)<br>
else;<br>
(如果沒有產生錯誤的處理方式)<br>
finally;<br>
(不管錯誤或執行正確，皆會進入處理方式)<br>

In [31]:
try:
  a=5
  b=10
  if a>b:
    print("a<b")
except NameError:
  print("名稱錯誤")
except ZeroDivisionError:
  print("除以0錯誤")  
except:
  print("錯誤產生")
else:
  print("程式正確沒有錯誤")
finally:
  print("程式結束")

程式正確沒有錯誤
程式結束


# **Untitled6** **檔案處理**
*   os套件:用來處理目錄與文件，以及檔案的讀寫

In [32]:
import os
os.getcwd() #回傳目前的工作目錄

'/content'

In [34]:
os.listdir(".") #列出目錄下所有的檔案

['.config', 'sample_data']

In [35]:
os.makedirs("test") #新增test目錄

In [36]:
os.rmdir("test") #移除test目錄
os.listdir(".")

['.config', 'sample_data']

# 檔案處理
os套件有自己的檔案處理命令，而比較常用的是python內建的open
*   python也有自己處理檔案的函式open(比較常用)     
*   w=可寫(預設建立檔案)若檔案存在則會清除舊檔案
*   w+=可寫可讀(預設建立檔案)若檔案存在則會清除舊檔案
*   r=可讀
*   r+=可寫可讀 但寫入資料指向開頭
*   a=可寫不能讀 但寫入資料指向尾端
*   a+=可寫可讀 但寫入資料指向尾端
*   b=轉進2進為文件
*   ab+=2進為文件的讀寫 寫入資料指向尾端

In [40]:
# 新增檔案
a=open("a.txt","w")
a.write("This is line1")
a.write("This is line2\n")
a.write("This is line3\n")
a.close()

In [41]:
os.path.isfile("a.txt")

True

In [39]:
a=open("a.txt","r")
print(a.readlines()) #一次讀取多行，與a.read()命令相同
a.close()

['This is line1This is line2\n', 'This is line3\n']


In [42]:
#加上檔案是否存在的判斷
if os.path.isfile("a.txt"):
  a=open("a.txt","r")
  print(a.readlines())
  a.close()
else:
  print("檔案不存在")

['This is line1This is line2\n', 'This is line3\n']


# 附加檔案

In [43]:
a=open("a.txt","a") #參數"a"會把寫入資訊附加在檔案尾巴
a.write("This is line4\n")
a.close()

In [44]:
a=open("a.txt","r")
print(a.readlines())
a.close()

['This is line1This is line2\n', 'This is line3\n', 'This is line4\n']


In [45]:
a=open("a.txt","r+") #參數"a"會把寫入資訊附加在檔案尾巴
a.write("This is line5\n")
a.close()

In [46]:
a=open("a.txt","r")
print(a.readlines())
a.close()

['This is line5\n', 'his is line2\n', 'This is line3\n', 'This is line4\n']


# **Untitled7 錯誤處理**

try:<br>
except:<br>
else:<br>
finally:<br>

In [47]:
a=10
b=20
if a<b:
    print(n)

NameError: ignored

In [48]:
a=10
b=20
try:
    if a<b:
        print(n)
except:
    print("錯誤產生")

錯誤產生


# 指定錯誤類別處理

In [49]:
a=10
b=20
try:
    if a<b:
        print(n)
except NameError as e:
    print("錯誤產生, 錯誤原因：",e)
except ZeroDivisionError:
    print("除以0錯誤")

錯誤產生, 錯誤原因： name 'n' is not defined


# else<br>
沒有錯誤產生會執行的部分

In [50]:
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生時會執行的部分")

沒有錯誤發生時會執行的部分


In [ ]:
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else:
    print("沒有錯誤發生時會執行的部分")
finally:
    print("不管有沒有錯誤一定會執行的部分")